/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.orms;


import nu.studer.sample.orms.tables.FlywaySchemaHistory;
import nu.studer.sample.orms.tables.UsersUsersAuthorities;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in orms.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index USERS_AUTHORITIES_IDX = Internal.createIndex(DSL.name("users_authorities_idx"), UsersUsersAuthorities.USERS_USERS_AUTHORITIES, new OrderField[] { UsersUsersAuthorities.USERS_USERS_AUTHORITIES.USER_ID, UsersUsersAuthorities.USERS_USERS_AUTHORITIES.AUTHORITY_ID }, true);
}
