/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.orms;


import java.util.Arrays;
import java.util.List;

import nu.studer.sample.DefaultCatalog;
import nu.studer.sample.orms.tables.FlywaySchemaHistory;
import nu.studer.sample.orms.tables.UsersAccountActivationToken;
import nu.studer.sample.orms.tables.UsersAuthorities;
import nu.studer.sample.orms.tables.UsersPasswordResetToken;
import nu.studer.sample.orms.tables.UsersUsers;
import nu.studer.sample.orms.tables.UsersUsersAuthorities;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orms extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>orms</code>
     */
    public static final Orms ORMS = new Orms();

    /**
     * The table <code>orms.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>orms.users_account_activation_token</code>.
     */
    public final UsersAccountActivationToken USERS_ACCOUNT_ACTIVATION_TOKEN = UsersAccountActivationToken.USERS_ACCOUNT_ACTIVATION_TOKEN;

    /**
     * The table <code>orms.users_authorities</code>.
     */
    public final UsersAuthorities USERS_AUTHORITIES = UsersAuthorities.USERS_AUTHORITIES;

    /**
     * The table <code>orms.users_password_reset_token</code>.
     */
    public final UsersPasswordResetToken USERS_PASSWORD_RESET_TOKEN = UsersPasswordResetToken.USERS_PASSWORD_RESET_TOKEN;

    /**
     * The table <code>orms.users_users</code>.
     */
    public final UsersUsers USERS_USERS = UsersUsers.USERS_USERS;

    /**
     * The table <code>orms.users_users_authorities</code>.
     */
    public final UsersUsersAuthorities USERS_USERS_AUTHORITIES = UsersUsersAuthorities.USERS_USERS_AUTHORITIES;

    /**
     * No further instances allowed
     */
    private Orms() {
        super("orms", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            UsersAccountActivationToken.USERS_ACCOUNT_ACTIVATION_TOKEN,
            UsersAuthorities.USERS_AUTHORITIES,
            UsersPasswordResetToken.USERS_PASSWORD_RESET_TOKEN,
            UsersUsers.USERS_USERS,
            UsersUsersAuthorities.USERS_USERS_AUTHORITIES
        );
    }
}
