/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.orms;


import nu.studer.sample.orms.tables.FlywaySchemaHistory;
import nu.studer.sample.orms.tables.UsersAccountActivationToken;
import nu.studer.sample.orms.tables.UsersAuthorities;
import nu.studer.sample.orms.tables.UsersPasswordResetToken;
import nu.studer.sample.orms.tables.UsersUsers;
import nu.studer.sample.orms.tables.UsersUsersAuthorities;


/**
 * Convenience access to all tables in orms.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>orms.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>orms.users_account_activation_token</code>.
     */
    public static final UsersAccountActivationToken USERS_ACCOUNT_ACTIVATION_TOKEN = UsersAccountActivationToken.USERS_ACCOUNT_ACTIVATION_TOKEN;

    /**
     * The table <code>orms.users_authorities</code>.
     */
    public static final UsersAuthorities USERS_AUTHORITIES = UsersAuthorities.USERS_AUTHORITIES;

    /**
     * The table <code>orms.users_password_reset_token</code>.
     */
    public static final UsersPasswordResetToken USERS_PASSWORD_RESET_TOKEN = UsersPasswordResetToken.USERS_PASSWORD_RESET_TOKEN;

    /**
     * The table <code>orms.users_users</code>.
     */
    public static final UsersUsers USERS_USERS = UsersUsers.USERS_USERS;

    /**
     * The table <code>orms.users_users_authorities</code>.
     */
    public static final UsersUsersAuthorities USERS_USERS_AUTHORITIES = UsersUsersAuthorities.USERS_USERS_AUTHORITIES;
}
