/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.information_schema.tables;


import nu.studer.sample.information_schema.InformationSchema;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDefinedTypes extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>information_schema.user_defined_types</code>
     */
    public static final UserDefinedTypes USER_DEFINED_TYPES = new UserDefinedTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column
     * <code>information_schema.user_defined_types.user_defined_type_catalog</code>.
     */
    public final TableField<Record, String> USER_DEFINED_TYPE_CATALOG = createField(DSL.name("user_defined_type_catalog"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.user_defined_type_schema</code>.
     */
    public final TableField<Record, String> USER_DEFINED_TYPE_SCHEMA = createField(DSL.name("user_defined_type_schema"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.user_defined_type_name</code>.
     */
    public final TableField<Record, String> USER_DEFINED_TYPE_NAME = createField(DSL.name("user_defined_type_name"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.user_defined_type_category</code>.
     */
    public final TableField<Record, String> USER_DEFINED_TYPE_CATEGORY = createField(DSL.name("user_defined_type_category"), nu.studer.sample.information_schema.Domains.CHARACTER_DATA.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.is_instantiable</code>.
     */
    public final TableField<Record, String> IS_INSTANTIABLE = createField(DSL.name("is_instantiable"), nu.studer.sample.information_schema.Domains.YES_OR_NO.getDataType(), this, "");

    /**
     * The column <code>information_schema.user_defined_types.is_final</code>.
     */
    public final TableField<Record, String> IS_FINAL = createField(DSL.name("is_final"), nu.studer.sample.information_schema.Domains.YES_OR_NO.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.ordering_form</code>.
     */
    public final TableField<Record, String> ORDERING_FORM = createField(DSL.name("ordering_form"), nu.studer.sample.information_schema.Domains.CHARACTER_DATA.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.ordering_category</code>.
     */
    public final TableField<Record, String> ORDERING_CATEGORY = createField(DSL.name("ordering_category"), nu.studer.sample.information_schema.Domains.CHARACTER_DATA.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.ordering_routine_catalog</code>.
     */
    public final TableField<Record, String> ORDERING_ROUTINE_CATALOG = createField(DSL.name("ordering_routine_catalog"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.ordering_routine_schema</code>.
     */
    public final TableField<Record, String> ORDERING_ROUTINE_SCHEMA = createField(DSL.name("ordering_routine_schema"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.ordering_routine_name</code>.
     */
    public final TableField<Record, String> ORDERING_ROUTINE_NAME = createField(DSL.name("ordering_routine_name"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.reference_type</code>.
     */
    public final TableField<Record, String> REFERENCE_TYPE = createField(DSL.name("reference_type"), nu.studer.sample.information_schema.Domains.CHARACTER_DATA.getDataType(), this, "");

    /**
     * The column <code>information_schema.user_defined_types.data_type</code>.
     */
    public final TableField<Record, String> DATA_TYPE = createField(DSL.name("data_type"), nu.studer.sample.information_schema.Domains.CHARACTER_DATA.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.character_maximum_length</code>.
     */
    public final TableField<Record, Integer> CHARACTER_MAXIMUM_LENGTH = createField(DSL.name("character_maximum_length"), nu.studer.sample.information_schema.Domains.CARDINAL_NUMBER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.character_octet_length</code>.
     */
    public final TableField<Record, Integer> CHARACTER_OCTET_LENGTH = createField(DSL.name("character_octet_length"), nu.studer.sample.information_schema.Domains.CARDINAL_NUMBER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.character_set_catalog</code>.
     */
    public final TableField<Record, String> CHARACTER_SET_CATALOG = createField(DSL.name("character_set_catalog"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.character_set_schema</code>.
     */
    public final TableField<Record, String> CHARACTER_SET_SCHEMA = createField(DSL.name("character_set_schema"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.character_set_name</code>.
     */
    public final TableField<Record, String> CHARACTER_SET_NAME = createField(DSL.name("character_set_name"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.collation_catalog</code>.
     */
    public final TableField<Record, String> COLLATION_CATALOG = createField(DSL.name("collation_catalog"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.collation_schema</code>.
     */
    public final TableField<Record, String> COLLATION_SCHEMA = createField(DSL.name("collation_schema"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.collation_name</code>.
     */
    public final TableField<Record, String> COLLATION_NAME = createField(DSL.name("collation_name"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.numeric_precision</code>.
     */
    public final TableField<Record, Integer> NUMERIC_PRECISION = createField(DSL.name("numeric_precision"), nu.studer.sample.information_schema.Domains.CARDINAL_NUMBER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.numeric_precision_radix</code>.
     */
    public final TableField<Record, Integer> NUMERIC_PRECISION_RADIX = createField(DSL.name("numeric_precision_radix"), nu.studer.sample.information_schema.Domains.CARDINAL_NUMBER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.numeric_scale</code>.
     */
    public final TableField<Record, Integer> NUMERIC_SCALE = createField(DSL.name("numeric_scale"), nu.studer.sample.information_schema.Domains.CARDINAL_NUMBER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.datetime_precision</code>.
     */
    public final TableField<Record, Integer> DATETIME_PRECISION = createField(DSL.name("datetime_precision"), nu.studer.sample.information_schema.Domains.CARDINAL_NUMBER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.interval_type</code>.
     */
    public final TableField<Record, String> INTERVAL_TYPE = createField(DSL.name("interval_type"), nu.studer.sample.information_schema.Domains.CHARACTER_DATA.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.interval_precision</code>.
     */
    public final TableField<Record, Integer> INTERVAL_PRECISION = createField(DSL.name("interval_precision"), nu.studer.sample.information_schema.Domains.CARDINAL_NUMBER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.source_dtd_identifier</code>.
     */
    public final TableField<Record, String> SOURCE_DTD_IDENTIFIER = createField(DSL.name("source_dtd_identifier"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    /**
     * The column
     * <code>information_schema.user_defined_types.ref_dtd_identifier</code>.
     */
    public final TableField<Record, String> REF_DTD_IDENTIFIER = createField(DSL.name("ref_dtd_identifier"), nu.studer.sample.information_schema.Domains.SQL_IDENTIFIER.getDataType(), this, "");

    private UserDefinedTypes(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private UserDefinedTypes(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "user_defined_types" as  SELECT (current_database())::information_schema.sql_identifier AS user_defined_type_catalog,
          (n.nspname)::information_schema.sql_identifier AS user_defined_type_schema,
          (c.relname)::information_schema.sql_identifier AS user_defined_type_name,
          ('STRUCTURED'::character varying)::information_schema.character_data AS user_defined_type_category,
          ('YES'::character varying)::information_schema.yes_or_no AS is_instantiable,
          (NULL::character varying)::information_schema.yes_or_no AS is_final,
          (NULL::character varying)::information_schema.character_data AS ordering_form,
          (NULL::character varying)::information_schema.character_data AS ordering_category,
          (NULL::name)::information_schema.sql_identifier AS ordering_routine_catalog,
          (NULL::name)::information_schema.sql_identifier AS ordering_routine_schema,
          (NULL::name)::information_schema.sql_identifier AS ordering_routine_name,
          (NULL::character varying)::information_schema.character_data AS reference_type,
          (NULL::character varying)::information_schema.character_data AS data_type,
          (NULL::integer)::information_schema.cardinal_number AS character_maximum_length,
          (NULL::integer)::information_schema.cardinal_number AS character_octet_length,
          (NULL::name)::information_schema.sql_identifier AS character_set_catalog,
          (NULL::name)::information_schema.sql_identifier AS character_set_schema,
          (NULL::name)::information_schema.sql_identifier AS character_set_name,
          (NULL::name)::information_schema.sql_identifier AS collation_catalog,
          (NULL::name)::information_schema.sql_identifier AS collation_schema,
          (NULL::name)::information_schema.sql_identifier AS collation_name,
          (NULL::integer)::information_schema.cardinal_number AS numeric_precision,
          (NULL::integer)::information_schema.cardinal_number AS numeric_precision_radix,
          (NULL::integer)::information_schema.cardinal_number AS numeric_scale,
          (NULL::integer)::information_schema.cardinal_number AS datetime_precision,
          (NULL::character varying)::information_schema.character_data AS interval_type,
          (NULL::integer)::information_schema.cardinal_number AS interval_precision,
          (NULL::name)::information_schema.sql_identifier AS source_dtd_identifier,
          (NULL::name)::information_schema.sql_identifier AS ref_dtd_identifier
         FROM pg_namespace n,
          pg_class c,
          pg_type t
        WHERE ((n.oid = c.relnamespace) AND (t.typrelid = c.oid) AND (c.relkind = 'c'::"char") AND (pg_has_role(t.typowner, 'USAGE'::text) OR has_type_privilege(t.oid, 'USAGE'::text)));
        """));
    }

    /**
     * Create an aliased <code>information_schema.user_defined_types</code>
     * table reference
     */
    public UserDefinedTypes(String alias) {
        this(DSL.name(alias), USER_DEFINED_TYPES);
    }

    /**
     * Create an aliased <code>information_schema.user_defined_types</code>
     * table reference
     */
    public UserDefinedTypes(Name alias) {
        this(alias, USER_DEFINED_TYPES);
    }

    /**
     * Create a <code>information_schema.user_defined_types</code> table
     * reference
     */
    public UserDefinedTypes() {
        this(DSL.name("user_defined_types"), null);
    }

    public <O extends Record> UserDefinedTypes(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, USER_DEFINED_TYPES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : InformationSchema.INFORMATION_SCHEMA;
    }

    @Override
    public UserDefinedTypes as(String alias) {
        return new UserDefinedTypes(DSL.name(alias), this);
    }

    @Override
    public UserDefinedTypes as(Name alias) {
        return new UserDefinedTypes(alias, this);
    }

    @Override
    public UserDefinedTypes as(Table<?> alias) {
        return new UserDefinedTypes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDefinedTypes rename(String name) {
        return new UserDefinedTypes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDefinedTypes rename(Name name) {
        return new UserDefinedTypes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDefinedTypes rename(Table<?> name) {
        return new UserDefinedTypes(name.getQualifiedName(), null);
    }
}
